const express = require("express");
const router = express.Router();
const incidenciasController = require("../controllers/incidenciasController");
router.post("/incidencias", incidenciasController.registrarIncidencia);
router.get("/incidencias", incidenciasController.listarIncidencias);
router.get("/incidencias/:id", incidenciasController.buscarIncidenciaPorId);
router.get("/incidencias/:id/clasificacion", incidenciasController.obtenerClasificacion);
router.put("/incidencias/:id/estado", incidenciasController.cambiarEstadoIncidencia);
router.delete("/incidencias/:id", incidenciasController.eliminarIncidencia);
router.get("/estadisticas", incidenciasController.obtenerEstadisticas);
module.exports = router;
